# Generated by Django 4.2 on 2023-05-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ-นามสกุล')),
                ('title', models.CharField(max_length=255, verbose_name='เรื่อง')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('email', models.CharField(max_length=255, verbose_name='อีเมล')),
                ('done', models.BooleanField(default=False, verbose_name='ดำเนินการแล้ว')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='สรุปผล')),
            ],
        ),
    ]
